# == This file defines the page layouts for new pages.
#
# For further information please see https://guides.alchemy-cms.com/pages.html

- name: homepage
  unique: true

  elements:
    - hero
    - rich_text

- name: standard
  elements:
    - hero
    - rich_text
    - carousel
    - tile
    - google_map
